PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += \
system/app/CarEvsCameraPreviewApp/CarEvsCameraPreviewApp.apk \
system/app/SampleRearViewCamera/SampleRearViewCamera.apk \
system/app/SampleRearViewCamera/oat/arm64/SampleRearViewCamera.odex \
system/app/SampleRearViewCamera/oat/arm64/SampleRearViewCamera.vdex \
system/bin/android.frameworks.automotive.display@1.0-service \
system/bin/evsmanagerd \
system/bin/gppservice \
system/bin/mixerops_objdump \
system/bin/qseecom_sample_client_system \
system/bin/test-mixer \
system/bin/test-resampler \
system/etc/diwali_power_sanity.xml \
system/etc/gpp_app_list \
system/etc/init/gppservice.rc \
system/etc/init.graphics.test.rc \
system/etc/init.qcom.testscripts.sh \
system/etc/init/android.frameworks.automotive.display@1.0-service.rc \
system/etc/init/evsmanagerd.rc \
system/etc/init/init.graphics.test.rc \
system/etc/kalama_power_sanity.xml \
system/etc/seccomp_policy/gppservice.policy \
system/etc/permissions/android.hardware.ethernet.xml \
system/etc/permissions/privapp-permissions-qti.xml \
system/etc/sysconfig/preinstalled-packages-platform-full-base.xml \
system/etc/sysconfig/qti_whitelist.xml \
system/etc/vintf/manifest/manifest_android.frameworks.automotive.display@1.0.xml \
system/etc/vintf/manifest/manifest_evsmanagerd.xml \
system/etc/waipio_power_sanity.xml \
system/framework/QPerformance.jar \
system/framework/oat/arm64/vendor.qti.data.txpwrservice-V1-java.odex \
system/framework/oat/arm64/vendor.qti.data.txpwrservice-V1-java.vdex \
system/framework/oat/arm64/vendor.qti.data.txpwrservice-V2-java.odex \
system/framework/oat/arm64/vendor.qti.data.txpwrservice-V2-java.vdex \
system/framework/oat/arm64/vendor.qti.data.txpwrservice-V3-java.odex \
system/framework/oat/arm64/vendor.qti.data.txpwrservice-V3-java.vdex \
system/framework/oat/arm64/vendor.qti.data.txpwrservice-V4-java.odex \
system/framework/oat/arm64/vendor.qti.data.txpwrservice-V4-java.vdex \
system/framework/oat/arm64/vendor.qti.data.txpwrservice-V5-java.odex \
system/framework/oat/arm64/vendor.qti.data.txpwrservice-V5-java.vdex \
system/framework/oat/arm64/vendor.qti.data.txpwrservice-V6-java.odex \
system/framework/oat/arm64/vendor.qti.data.txpwrservice-V6-java.vdex \
system/framework/vendor.qti.data.txpwrservice-V1-java.jar \
system/framework/vendor.qti.data.txpwrservice-V2-java.jar \
system/framework/vendor.qti.data.txpwrservice-V3-java.jar \
system/framework/vendor.qti.data.txpwrservice-V4-java.jar \
system/framework/vendor.qti.data.txpwrservice-V5-java.jar \
system/framework/vendor.qti.data.txpwrservice-V6-java.jar \
system/lib64/android.frameworks.automotive.display@1.0.so \
system/lib64/android.frameworks.automotive.powerpolicy-V2-ndk.so \
system/lib64/android.frameworks.automotive.telemetry-V1-ndk.so \
system/lib64/android.hardware.audio.common@4.0-util.so \
system/lib64/android.hardware.audio.common@4.0.so \
system/lib64/android.hardware.audio.common@5.0-util.so \
system/lib64/android.hardware.audio.common@5.0.so \
system/lib64/android.hardware.audio.effect@4.0.so \
system/lib64/android.hardware.audio.effect@5.0.so \
system/lib64/android.hardware.audio@4.0.so \
system/lib64/android.hardware.audio@5.0.so \
system/lib64/android.hardware.automotive.evs-V1-ndk.so \
system/lib64/android.hardware.automotive.evs@1.0.so \
system/lib64/android.hardware.automotive.evs@1.1.so \
system/lib64/android.hardware.graphics.common-V4-ndk.so \
system/lib64/android.hardware.graphics.common-V5-ndk.so \
system/lib64/android.hardware.sensors@2.0-ScopedWakelock.so \
system/lib64/android.hardware.thermal-V2-ndk.so \
system/lib64/android.hardware.thermal@2.0.so \
system/lib64/libminijail_rust.dylib.so \
system/lib64/libminijail_sys.dylib.so \
system/lib64/libMotionEngine.so \
system/lib64/libMotionEngineVk.so \
system/lib64/libgppextension.so \
system/lib64/libgpppreprocessing.so \
system/lib64/libgpptxr.so \
system/lib64/libgppvppgfrcplussession.so \
system/lib64/libsimplelog.dylib.so \
system/lib64/libstatslog_evsmanagerd.so \
system/lib64/libtermcolor.dylib.so \
system/lib64/libvhalclient.so \
system/lib64/vendor.qti.data.txpwrservice-V1-ndk.so \
system/lib64/vendor.qti.data.txpwrservice-V2-ndk.so \
system/lib64/vendor.qti.data.txpwrservice-V3-ndk.so \
system/lib64/vendor.qti.data.txpwrservice-V4-ndk.so \
system/lib64/vendor.qti.data.txpwrservice-V5-ndk.so \
system/lib64/vendor.qti.data.txpwrservice-V6-ndk.so \
system/lib64/vendor.qti.diaghal-V1-ndk.so \
system/lib64/vendor.qti.hardware.display.snapallocext-V1-ndk.so \
system/lib64/vendor.qti.hardware.perf2-V1-ndk.so \
system/lib64/vendor.qti.hardware.systemhelperaidl-V1-ndk.so \
system/priv-app/DynamicSystemInstallationService/DynamicSystemInstallationService.apk \
system/priv-app/DynamicSystemInstallationService/oat/arm64/DynamicSystemInstallationService.odex \
system/priv-app/DynamicSystemInstallationService/oat/arm64/DynamicSystemInstallationService.vdex \
system/usr/keylayout/gpio-keys.kl \

# Add list only if GAS is enabled.
ifeq ($(TARGET_USES_GAS),true)
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += \
system/apex/com.android.extservices.gms.capex \
system/apex/com.android.permission.gms.capex \
system/app/GoogleExtShared/GoogleExtShared.apk \
system/app/GoogleExtShared/oat/arm64/GoogleExtShared.odex \
system/app/GoogleExtShared/oat/arm64/GoogleExtShared.vdex \
system/etc/permissions/privapp-permissions-google.xml \
system/priv-app/GooglePackageInstaller/GooglePackageInstaller.apk \
system/priv-app/GooglePackageInstaller/oat/arm64/GooglePackageInstaller.odex \
system/priv-app/GooglePackageInstaller/oat/arm64/GooglePackageInstaller.vdex
endif
